name: Sandbox Start Creation

on:
  workflow_dispatch:
    inputs:
      sandboxName: 
        description: Name of the sandbox to be created
        type: string
        required: true
      licenseType:
        description: Type of sandbox license. Could be Developer, Developer_Pro, Partial, and Full
        type: choice
        required: true
        options:
        - Developer
        - Developer_Pro
        - Partial
        - Full

# Jobs to be executed
jobs:
  sandbox-creation-start:
    runs-on: ubuntu-latest
    container: tnascimento013/latam_salesforcedx_industries_orgdevmodebuilds:latest
    environment: prod
    steps:

      - name: Extracting private key
        run: 'echo "${{ secrets.JWT_KEY_PROD }}" > server.key'

      - name: Authenticate on production
        run: sf org login jwt --instance-url https://login.salesforce.com --client-id ${{ vars.CLIENT_ID }} --username ${{ vars.USERNAME }} --jwt-key-file server.key --alias prodOrg

      - name: Start the process to create the sandbox
        run: sf org create sandbox --name ${{ inputs.sandboxName }} --license-type ${{ inputs.licenseType }} --alias sdbx --target-org prodOrg --async

